language: java
jdk: oraclejdk8
install: true

jobs:
  include:
    - stage: build
      script: ./gradlew build
    - stage: test
      script: ./gradlew test
    - stage: bootstrap
      script: ./gradlew bootstrap
    - stage: build-2
      script: ./gradlew build
    - stage: test-2
      script: ./gradlew test
